[package]
name = "hagency-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
hagency-contract.workspace = true
hagency-operations.workspace = true
palpo.workspace = true
pasion-backend.workspace = true
pasion-config.workspace = true
pasion-data.workspace = true
zeroize.workspace = true
figment.workspace = true
camino.workspace = true
rand_chacha.workspace = true
rand_core.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry.workspace = true
rustls.workspace = true
salvo.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
reqwest.workspace = true
diesel.workspace = true
diesel-async.workspace = true
chrono.workspace = true
url.workspace = true
uuid.workspace = true
rand.workspace = true
sha2.workspace = true
base64.workspace = true
regex.workspace = true
subtle.workspace = true
aes-gcm.workspace = true
hex.workspace = true
unicode-normalization.workspace = true

percent-encoding.workspace = true

[dev-dependencies]
tempfile.workspace = true
